# Generated by Django 4.2.7 on 2025-07-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking_app', '0002_booking_duration_minutes_booking_vehicle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('sensor', 'Parking Sensor'), ('gate', 'Entry/Exit Gate'), ('display', 'LED Display'), ('camera', 'Camera')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_app.parkinglot')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_app.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField()),
                ('distance_cm', models.FloatField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_integration.iotdevice')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_app.parkingspot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_integration.iotdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
