# Generated by Django 4.2.7 on 2025-07-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="ir_alert",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="slot1_occupied",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="slot2_occupied",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
