# Generated by Django 4.2.7 on 2025-11-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_integration', '0002_add_dual_sensor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
