# Generated by Django 4.2.7 on 2025-07-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="vehicle_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="car_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
