# Generated by Django 4.2.7 on 2025-08-22 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking_app", "0002_booking_duration_minutes_booking_vehicle_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="car_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="license_plate",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_password_reset",
            field=models.DateTimeField(
                blank=True, help_text="When the password was last reset", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
