# Generated by Django 4.2.7 on 2025-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0003_remove_userprofile_car_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_overtime",
            field=models.BooleanField(
                default=False, help_text="Whether the booking is currently in overtime"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="overtime_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost for overtime parking",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="overtime_minutes",
            field=models.IntegerField(
                default=0, help_text="Minutes parked beyond booking time"
            ),
        ),
    ]
