# Generated by Django 4.2.7 on 2025-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0004_booking_is_overtime_booking_overtime_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="iot_overtime_end",
            field=models.DateTimeField(
                blank=True,
                help_text="When IoT detected green light (car left)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="iot_overtime_start",
            field=models.DateTimeField(
                blank=True,
                help_text="When IoT detected red light (car still parked)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="overtime_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When overtime billing actually started (5 seconds after expiry)",
                null=True,
            ),
        ),
    ]
