# Generated by Django 4.2.7 on 2025-09-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parking_app",
            "0005_booking_iot_overtime_end_booking_iot_overtime_start_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="grace_period_ended",
            field=models.DateTimeField(
                blank=True, help_text="When the 10-second grace period ended", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="grace_period_started",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 10-second grace period started",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="timer_started",
            field=models.DateTimeField(
                blank=True,
                help_text="When the countdown timer actually started",
                null=True,
            ),
        ),
    ]
