# Generated by Django 4.2.7 on 2025-09-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0007_booking_last_billing_at_userprofile_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the booking was completed", null=True
            ),
        ),
    ]
