# Generated by Django 4.2.7 on 2025-10-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0009_userreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="number_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
