# Generated by Django 4.2.7 on 2025-10-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0010_userprofile_license_number_userprofile_number_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="number_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
